- scss/components/_lab-radio.scss
**Related to:** https://github.com/labcodes/confetti-storybook/pull/5
**Link to task:** https://labcodes.atlassian.net/browse/CSYS-202
**Staging app:** https://migrate-radio--labstorybook-master.netlify.app/
- open the staging app
- verify that radios with ariaDisabled true behave the same as the disabled ones
Added selectors for aria-disabled radios and disabled pointer events for radios with aria-disabled true.
> CSYS-202: Migrate radio

- src/Alert.js
- src/Banner.js
**Related to:**
https://github.com/labcodes/confetti-storybook/pull/13
https://labcodes.atlassian.net/browse/CSYS-206
**Staging app:**
https://migrate-system-message--labstorybook-master.netlify.app/
Run the tests, check if all pass. Go to the staging app, try different combinations of `icon` in `System Message` section.
This PR enables `icon` props from `Alert` and `Banner` to be selectable.
> CSYS-206: Migrate System Message

- scss/base/_forms.scss
- scss/base/_links.scss
- scss/base/_titles.scss
- scss/components/_lab-alerts.scss
- scss/components/_lab-button.scss
- scss/components/_lab-card.scss
- scss/components/_lab-checkbox.scss
- scss/components/_lab-dialog.scss
- scss/components/_lab-inputs.scss
- scss/components/_lab-radio.scss
- scss/components/_lab-sidebar.scss
- scss/components/_lab-tag.scss
- scss/components/_lab-tooltip.scss
- scss/variables/_typography.scss
**Link to task:** https://labcodes.atlassian.net/browse/CSYS-280
**Staging app:** https://fix-typography--labstorybook-master.netlify.app/
- Check all texts on components and `<legend>` to check if numbers have the same height of the letters or if they are with ascendants and descendants.
- Check if `<legend>` is using the DSYS font and styles
- Check if the fallback font is working.
- Add font property to align numbers
- Add Merriwether and Merriwether Sans as fallback font
- Add styles for `<legend>`
> CSYS-280 Fix typography

- src/Card/CardHeader.js
- src/Card/CardHeader.test.js
- src/Card/__snapshots__/CardHeader.test.js.snap
https://labcodes.atlassian.net/browse/CSYS-267
**Staging app:**
https://migrate-card-changes--labstorybook-master.netlify.app/
Check if `Card` docummentation reflect the changes introduced by branch `card-qa` from `labstorybook` repo.
Apply changes introduced by `labstorybook:card-qa` <https://github.com/labcodes/labstorybook/pull/104>.
> CSYS-267: Migrate Card changes

- README.md
- package.json
**Link to task:** https://labcodes.atlassian.net/browse/CSYS-282
- check the files changed for improvements on readme and npm scripts.
Changed naming for the package and version, added npm scripts to publish the package as alpha or beta.
> CSYS-282: Npm config

- scss/components/_lab-card.scss
- src/Card/FilledCard.js
- src/Card/FilledCard.test.js
- src/Card/OutlineCard.js
- src/Card/OutlineCard.test.js
- src/Card/OutlineFilledCard.js
- src/Card/OutlineFilledCard.test.js
- src/Card/__snapshots__/FilledCard.test.js.snap
- src/Card/__snapshots__/OutlineCard.test.js.snap
- src/Card/__snapshots__/OutlineFilledCard.test.js.snap
https://labcodes.atlassian.net/browse/CSYS-285
Install the application locally, and check if `isHorizontal` property of `Card` components can be applied on mobile screens.
This PR removes the media query for applying `isHorizontal` property from tablet sizes and above. With that, such a property is applied for all screen sizes.
> CSYS-285: fix-card

- package.json
- scss/main.scss
https://labcodes.atlassian.net/browse/CSYS-292
This PR updates the bulma version from 0.9.1 to 0.9.2 and includes the `bulma/sass/base/_all.scss` file in the imports.
> CSYS-292: Fix bulma

- package.json
**Link to task:** [Card on Jira](https://labcodes.atlassian.net/jira/software/c/projects/CSYS/boards/63?modal=detail&selectedIssue=CSYS-302)
This PR aims to fix the code conflict w/ git submodules. These updates will improve the commit reference between the ds and Storybook.
> feat: updating package's version

- PULL_REQUEST_TEMPLATE.md
[CSYS#309](https://labcodes.atlassian.net/browse/CSYS-309)
Access the above url and it should work.
I just changed  https://your-branch--labstorybook-master.netlify.app/ to https://your-branch--confetti-storybook.netlify.app/
> [CSYS#309] Update branch URL at pull_request_template

- src/Button/AbstractButton.js
**Link to task:** [Card #320](https://labcodes.atlassian.net/browse/CSYS-320)
**How to test:** Run the project at the `confetti-storybook` and click at Button's subcomponents. Also test the component's attributes to check if all of them are working.
**Description of your solution:** Refactoring the component from Class to Function component.
**Screenshots (when applicable):** NA
> [CSYS-320] Migrate Abstract Button

- src/Button/Button.js
**Link to task:** [Card #321 from Jira](https://labcodes.atlassian.net/browse/CSYS-321)
**How to test:** Run the project @ `confetti-storybook` folder and test all the attributes.
**Description of your solution:** Removing mentions to the class components 
> [CSYS-321] Migrating Button component

- src/Button/OutlineButton.js
**Link to task:** [Card 322 from Jira](https://labcodes.atlassian.net/browse/CSYS-322)
**How to test:** Run the project @ confetti-storybook folder and test all the Outline Button's attributes.
**Description of your solution:** Removing mentions to the class components and refactoring to the functional component.
> [CSYS-322] OutlineButton to function component

- src/Button/TextButton.js
**Link to task:** [Card #323 from Jira](https://labcodes.atlassian.net/jira/software/c/projects/CSYS/boards/63?modal=detail&selectedIssue=CSYS-323) 
**How to test:** Run the project @ confetti-storybook folder and test all the Outline Button's attributes.
Description of your solution: Removing mentions to the class components and refactoring to the functional component.
> [CSYS-323] Migrating Text Button

- src/Card/CardDivider.js
- src/Card/CardHeader.js
- src/Card/CardImage.js
- src/Card/DoubleAction.js
- src/Card/DoubleAction.test.js
- src/Card/FilledCard.js
- src/Card/LinkAction.js
- src/Card/OutlineCard.js
- src/Card/OutlineFilledCard.js
- src/Card/__snapshots__/DoubleAction.test.js.snap
- src/Card/__snapshots__/FilledCard.test.js.snap
- src/Card/__snapshots__/OutlineFilledCard.test.js.snap
**Link to task:** [Card #313 from Jira](https://labcodes.atlassian.net/browse/CSYS-313)
**Staging app:** https://csys-313-migrate-card-components--confetti-storybook.netlify.app/
**How to test:** Run `npm start` and `npm runtest` to check if the component (and its subcomponents) works as expected.
Replacement from lifecycle React's methods to Hooks and other minor refactors. 
**Screenshots (when applicable):** NA
> [CSYS-313] Migrating Card components

- src/Icon.js
- src/Icon.test.js
Link to task:
[CSYS-355](https://labcodes.atlassian.net/browse/CSYS-359)
Staging app: https://CSYS-359-migrate-icon--confetti-storybook.netlify.app/
How to test:
After running your project locally, run the Alert.test.jsto check if the Alert component is working as expected.
Screenshots (when applicable): NA
> [CSYS-359] Migrating Icon component to Hooks

- src/Radio.js
Link to task:
[CSYS-360](https://labcodes.atlassian.net/browse/CSYS-360)
Staging app: https://csys-359-migrate-icon--confetti-storybook.netlify.app/
How to test:
After running your project locally, run the `Radio.test.js` to check if the Alert component is working as expected.
Screenshots (when applicable): NA
> [CSYS-360] Migrating Radio component to Hooks

- src/Card/__snapshots__/CardHeader.test.js.snap
- src/Dropdown/TagDropdownTrigger.js
- src/Tags/AbstractTag.js
- src/Tags/DropdownTag.js
- src/Tags/RemovableTag.js
- src/Tags/SimpleTag.js
- src/Tags/TogglableTag.js
Link to task: [Card from Jira](https://labcodes.atlassian.net/browse/CSYS-318)
Staging app:
https://CSYS-318-migrate-tag-components--confetti-storybook.netlify.app/
How to test:
Run the project locally and check if the Tag's subcomponents are working as expected.
Removing Class Components' methods and using Hooks to control the states and other properties.
Screenshots (when applicable):
N/A
> [CSYS-318] Migrating Tag components

- src/Alert.js
- src/__snapshots__/Alert.test.js.snap
Link to task:
[CSYS-355](https://labcodes.atlassian.net/browse/CSYS-355)
Staging app: https://CSYS-355-migrate-alert--confetti-storybook.netlify.app/
How to test:
After running your project locally, run the `Icon.test.js`to check if the Alert component is working as expected.
Screenshots (when applicable):
> [CSYS-355] Migrating Alert component

- src/Toggle.js
Link to task:
[CSYS-361](https://labcodes.atlassian.net/browse/CSYS-361)
Staging app: https://csys-361-migrate-toggle--confetti-storybook.netlify.app/
How to test:
After running your project locally, run the Toggle.test.js to check if the Alert component is working as expected.
Screenshots (when applicable): NA
> [CSYS-361] Migrating Toggle component to Hooks

- src/Tooltip.js
Link to task:
[CSYS-362](https://labcodes.atlassian.net/browse/CSYS-362)
Staging app: https://CSYS-362-migrate-toggle--confetti-storybook.netlify.app/
How to test:
After running your project locally, run the Tooltip.test.js to check if the Alert component is working as expected.
Screenshots (when applicable): NA
> [CSYS-362] Migrating Tooltip to Hooks

- src/Input/EmailInput.js
**Staging app:** https://CSYS-344-migrate-email-input--confetti-storybook.netlify.app/
This PR migrates Email Input to function based Component
> [CSYS-344] Migrate email input

- src/Sidebar/Body.js
- src/Sidebar/CollapseButton.js
- src/Sidebar/Footer.js
- src/Sidebar/FooterButton.js
- src/Sidebar/Header.js
- src/Sidebar/Logotype.js
- src/Sidebar/NarrowSidebar.js
- src/Sidebar/UserAvatar.js
[JIRA#317](https://labcodes.atlassian.net/browse/CSYS-317)
**Staging app:** 
https://CSYS-317-migrate-sidebar-to-fn-component--confetti-storybook.netlify.app/
- Run all the tests to check if the component crash
I made the class to function component migration of the Sidebar component. It includes all of its subcomponents like Body, CollapseButton, Footer, Header, Item, LogoType, NarrowSidebar e UserAvatar. 
N/A
> [CSYS-317] Migrate Sidebar to function component

- src/Input/TextInput.js
[CSYS-346](https://labcodes.atlassian.net/browse/CSYS-346)
**Staging app:** https://CSYS-346-textinput-to-fn-component--confetti-storybook.netlify.app/
Just run all tests with `npm run test`
- Move all the propTypes and defaultProps to outside the function body.
- Change class statement to function
N/A
> [CSYS-346] Migrate TextInput.js from class to fn component

- src/Input/AbstractTextInput.js
- src/hooks.js
[JIRA#343](https://labcodes.atlassian.net/browse/CSYS-343)
**Staging app:** https://CSYS-343-AbstractTextInput-to-fn-component--confetti-storybook.netlify.app/
Run all the tests to check if the component crash
- I moved all the instructions that were at the constructor to the useEffect with no dependencies.
- Created a useEffect to run whenever value or isValid prop changes.
- Create a `previousLocalValue` to check if it should set a new value based on the `localValue !== previousLocalValue`. 
N/A
> [CSYS-343] Migrate AbstractTextInput to function component

- src/Input/PasswordInput.js
Reverts labcodes/confetti-ds#40
The #40 was closed **before** the reviewer's final approval.
After checking the correspondent branch on confetti-storybook, it wasn't noticed any further issues from the PR update.
> Revert "[CSYS-345] Migrate PasswordInput.js to function component"

- src/Tags/__snapshots__/AbstractTag.test.js.snap
- src/Tags/__snapshots__/DropdownTag.test.js.snap
- src/Tags/__snapshots__/RemovableTag.test.js.snap
- src/Tags/__snapshots__/SimpleTag.test.js.snap
- src/Tags/__snapshots__/TogglableTag.test.js.snap
- src/__snapshots__/Icon.test.js.snap
Test snapshots related to Tags were updated to properly use onKeyDown function instead of onKeyPress
> Fix tags snapshots from tests

- .github/workflows/ci.yml
- .gitignore
- packages/confetti-ds/jest.config.ts
**This list for internal reference. You can delete it for your PR :relieved:**
Before submitting this pull request, make sure these boxes are checked. Thanks!
Also provide the following information:
**Link to task:** https://labcodes.atlassian.net/browse/CSYS-463
> CSYS-394 - Run jest tests on Github Action
